-- MySQL Script generated by MySQL Workbench
-- Sun Sep  8 23:15:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maquina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `maquina` ;

-- -----------------------------------------------------
-- Schema maquina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maquina` DEFAULT CHARACTER SET utf8 ;
USE `maquina` ;

-- -----------------------------------------------------
-- Table `maquina`.`Puntada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maquina`.`Puntada` (
  `Id_libro` INT NOT NULL,
  `tipoDePuntada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_libro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maquina`.`Hilos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maquina`.`Hilos` (
  `idHilos` INT NOT NULL,
  `color` VARCHAR(45) NULL DEFAULT 'blanco',
  `largo_cm` INT NULL,
  PRIMARY KEY (`idHilos`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `largo_cm_UNIQUE` ON `maquina`.`Hilos` (`largo_cm` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `maquina`.`Maquina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maquina`.`Maquina` (
  `IdMaquina` INT NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  `Puntada_Id_libro` INT NOT NULL,
  `Hilos_idHilos` INT NOT NULL,
  `velocidad_maxima` INT NOT NULL,
  `velocidad_minima` INT NOT NULL,
  PRIMARY KEY (`IdMaquina`, `Puntada_Id_libro`, `Hilos_idHilos`),
  CONSTRAINT `fk_Maquina_Puntada`
    FOREIGN KEY (`Puntada_Id_libro`)
    REFERENCES `maquina`.`Puntada` (`Id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Maquina_Hilos1`
    FOREIGN KEY (`Hilos_idHilos`)
    REFERENCES `maquina`.`Hilos` (`idHilos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Maquina_Puntada_idx` ON `maquina`.`Maquina` (`Puntada_Id_libro` ASC) VISIBLE;

CREATE INDEX `fk_Maquina_Hilos1_idx` ON `maquina`.`Maquina` (`Hilos_idHilos` ASC) VISIBLE;

CREATE UNIQUE INDEX `velocidad_maxima_UNIQUE` ON `maquina`.`Maquina` (`velocidad_maxima` ASC) VISIBLE;

CREATE UNIQUE INDEX `velocidad_minima_UNIQUE` ON `maquina`.`Maquina` (`velocidad_minima` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
